name: GitHub Activity Graph

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate activity graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: PanatiNitesh
          options: >-
            theme=github-dark&hide_border=true&area=true&custom_title=GitHub%20Activity&days=30
          output_path: profile/activity-graph.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit graph
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Update GitHub activity graph"
          file_pattern: "profile/activity-graph.svg"
